sudo: required
services:
  - docker

before_install:
  - docker build -t kvsamsonov/react-test -f ./client/Dockerfile.dev ./react-app

script:
  - docker run -e CI=true kvsamsonov/react-test npm test

after_success:
  - docker build -t kvsamsonov/multi-client ./react-app
  - docker build -t kvsamsonov/multi-nginx ./nginx
  - docker build -t kvsamsonov/multi-server ./server
  - docker build -t kvsamsonov/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kvsamsonov/multi-client
  - docker push kvsamsonov/multi-nginx
  - docker push kvsamsonov/multi-server
  - docker push kvsamsonov/multi-worker
